#!/usr/bin/env ruby
# encoding: utf-8

description = <<-EOF
(」・ω・)」uh~b?
(／・ω・)／aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab?
ab?
321234 ?
ab?
ab?
lorem ipsum dolor sit amet consectetur adipiscing elit b?
a bb?
abcb?
0abcedf abcb?
EOF

description.split("\n").each_with_index do |line, i|
  puts "%3d : %s" % [i + 1, line]
end
